[package]
name = "sqrt_decomposition"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
algebraics = { path = "../../crates/algebraics" }
util = { path = "../../crates/util" }
itertools = "0.10.3"

[dev-dependencies]
rand = "0.8.5"
