[package]
name = "fenwick_tree"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
num-traits = "0.2.14"
util = { path = "../util" }
algebraics = { path = "../algebraics" }

[dev-dependencies]
rand = "0.8.5"