[package]
name = "fenwick_tree"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
num-traits = "=0.2.11"
util = { path = "../util" }
algebraic_structures = { path = "../algebraic_structures" }
