[package]
name = "sqrt_decomposition"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
algebraic_structures = { path = "../algebraic_structures" }
util = { path = "../util" }

[dev-dependencies]
rand = "0.8.5"
